version: "3.8"

services:
  postgres:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-post}
      - POSTGRES_DB=dev
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
