"""add_personal_email_address_column

Revision ID: 1430a1c974e2
Revises: 576fa9a092d9
Create Date: 2023-04-12 14:36:04.643075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

# revision identifiers, used by Alembic.
revision = '1430a1c974e2'
down_revision = '576fa9a092d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    recruits = table(
        "recruits",
        sa.Column("first_name", sa.VARCHAR(20)),
        sa.Column("surname", sa.VARCHAR(20)),
        sa.Column("personal_email_address", sa.VARCHAR(30)),
    )
    op.add_column(
        "recruits",
        sa.Column("personal_email_address", sa.VARCHAR(length=30), nullable=False),
    )
    op.create_unique_constraint(
        "uq_email_address", "recruits", ["personal_email_address"]
    )
    op.execute(
        recruits.update()
        .where(recruits.c.personal_email_address == None)
        .values(
            personal_email_address=(
                recruits.c.first_name + "." + recruits.c.surname + "@umuzi.org"
            )
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruits', type_='unique')
    op.drop_column('recruits', 'personal_email_address')
    # ### end Alembic commands ###
