"""delete_id_number_column

Revision ID: 48e912f35e8c
Revises: 21068c7b95ab
Create Date: 2023-04-12 23:14:32.755548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48e912f35e8c"
down_revision = "21068c7b95ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("recruits_id_number_key", "recruits", type_="unique")
    op.drop_column("recruits", "id_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruits",
        sa.Column(
            "id_number", sa.VARCHAR(length=13), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint("recruits_id_number_key", "recruits", ["id_number"])
    # ### end Alembic commands ###
