"""create_recruits_table

Revision ID: 576fa9a092d9
Revises: 
Create Date: 2023-04-12 14:14:57.073845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576fa9a092d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('chatname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('github_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=13), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatname'),
    sa.UniqueConstraint('github_name'),
    sa.UniqueConstraint('id_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruits')
    # ### end Alembic commands ###
