"""add_cohort_column

Revision ID: fa4e435b827d
Revises: 1430a1c974e2
Create Date: 2023-04-12 15:30:38.067883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

# revision identifiers, used by Alembic.
revision = "fa4e435b827d"
down_revision = "1430a1c974e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    recruits = table(
        "recruits",
        sa.Column("cohort", sa.VARCHAR(20)),
    )
    op.add_column(
        "recruits", sa.Column("cohort", sa.VARCHAR(length=20), nullable=True)
    )
    op.execute(
        recruits.update()
        .where(recruits.c.cohort == None)
        .values({"cohort":"C25 Data Eng"})
    )
    op.alter_column(table_name="recruits", column_name="cohort", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recruits", "cohort")
    # ### end Alembic commands ###
